services:
  - type: web
    name: myrehab
    runtime: node
    plan: starter
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: "22"
